@endpoint = https://pldlcqqrd8.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spacesId=ytbbubvvhg
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Paris",
    "name": "Good Holiday Venue"
}