@endpoint = https://pldlcqqrd8.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/spaces/
###

GET {{endpoint}}/spaces?spaceId=188f7c42-d463-4e87-b045-6fcd5f11e869
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Nigeria",
    "name": "Home town"
}
###

PUT {{endpoint}}/spaces?spaceId=64c87073-5ffe-4cbd-b867-2645b91fccde
Content-Type: application/json

{
    "location": "Jamaica",
    "name": "City of Ragae"
}
###

DELETE  {{endpoint}}/spaces?spaceId=64c87073-5ffe-4cbd-b867-2645b91fccde
###